library(tidyverse)
library(rgdal)
library(broom)

states <- readOGR("cb_2016_us_state_500k", "cb_2016_us_state_500k", verbose = F)
ct_shp <- subset(states, STUSPS == "CT")
town_shp <- readOGR("town_shp", "cb_2015_09_cousub_500k", verbose = F)
ct_tidy <- broom::tidy(ct_shp, region = "STUSPS")
town_tidy <- broom::tidy(town_shp, region = "NAME")
senate_shp <- readOGR("cb_2016_09_sldu_500k", "cb_2016_09_sldu_500k", verbose = F)
house_shp <- readOGR("cb_2016_09_sldl_500k", "cb_2016_09_sldl_500k", verbose = F)
senate_tidy <- broom::tidy(senate_shp, region = "AFFGEOID")
house_tidy <- broom::tidy(house_shp, region = "AFFGEOID")

write_csv(ct_tidy, "ct_tidy.csv")
write_csv(town_tidy, "town_tidy.csv")
write_csv(senate_tidy, "senate_tidy.csv")
write_csv(house_tidy, "house_tidy.csv")